fullnameOverride: "nginx-b-prod"
replicaCount: 3
image:
  repository: nginx
  tag: "1.22.0"
service:
  type: LoadBalancer
  port: 80
  targetPort: 80
config:
  index.html: |
    <html><body><h1>nginx-b - PROD</h1></body></html>
