fullnameOverride: "nginx-uat"
replicaCount: 1
image:
  repository: nginx
  tag: "1.21.6"
service:
  type: ClusterIP
  port: 80
  targetPort: 80
config:
  index.html: |
    <html><body><h1>nginx-a - UAT</h1></body></html>
